module.exports = {
  "apps": [
    {
      "name": "lariberrys",
      "script": "./single_instance.js",
      "instances": 1,
      "exec_mode": "fork",
      "env": {
        "INSTANCE_ID": "1",
        "PROXY_IP": "82.163.175.153",
        "PROXY_USERNAME": "kamzza",
        "PROXY_PASSWORD": "bJXwSnBLy9",
        "PROXY_PORT": "50101",
        "BACKUP_PROXY_IP": "77.47.240.226",
        "INSTAGRAM_SESSIONID": "74377058585%3A7gBhijBAe7qLvd%3A6%3AAYeiTK6JVYXn3Ej6A6yh3iyszU0EmV1aDXW-L1RUng",
        "INSTAGRAM_USERNAME": "lariberrys",
        "MAX_FOLLOWS_PER_HOUR": "25",
        "MAX_FOLLOWS_PER_DAY": "150",
        "MAX_LIKES_PER_DAY": "50",
        "FOLLOW_USER_RATIO_MIN": "0.0",
        "FOLLOW_USER_RATIO_MAX": "100.0",
        "MINIMUM_POST_COUNT": "0",
        "MAXIMUM_POST_COUNT": "999999",
        "SHOULD_LIKE_POSTS": "true",
        "POSTS_TO_LIKE": "2",
        "FOLLOW_USER_MIN_FOLLOWERS": "0",
        "FOLLOW_USER_MAX_FOLLOWERS": "1000000",
        "FOLLOW_USER_MIN_FOLLOWING": "0",
        "FOLLOW_USER_MAX_FOLLOWING": "1000000",
        "USERS_TO_FOLLOW": "lelasohnabaka,vixeniaaa,gonkgonk666,msliababy,grungeeaesth"
      },
      "error_file": "./logs/lariberrys.log",
      "time": false,
      "autorestart": true,
      "max_restarts": 10,
      "restart_delay": 5000
    },
    {
      "name": "miyaakln",
      "script": "./single_instance.js",
      "instances": 1,
      "exec_mode": "fork",
      "env": {
        "INSTANCE_ID": "2",
        "PROXY_IP": "161.77.68.134",
        "PROXY_USERNAME": "kamzza",
        "PROXY_PASSWORD": "bJXwSnBLy9",
        "PROXY_PORT": "50101",
        "BACKUP_PROXY_IP": "77.47.240.226",
        "INSTAGRAM_SESSIONID": "57245491009%3A2GRUC7iOmcmF1A%3A3%3AAYc9SloyqJdqmOSZDYjOF4OZIkiWTbVfVUOO7qYISw",
        "INSTAGRAM_USERNAME": "miyaakln",
        "MAX_FOLLOWS_PER_HOUR": "25",
        "MAX_FOLLOWS_PER_DAY": "150",
        "MAX_LIKES_PER_DAY": "50",
        "FOLLOW_USER_RATIO_MIN": "0.0",
        "FOLLOW_USER_RATIO_MAX": "100.0",
        "MINIMUM_POST_COUNT": "0",
        "MAXIMUM_POST_COUNT": "999999",
        "SHOULD_LIKE_POSTS": "true",
        "POSTS_TO_LIKE": "2",
        "FOLLOW_USER_MIN_FOLLOWERS": "0",
        "FOLLOW_USER_MAX_FOLLOWERS": "1000000",
        "FOLLOW_USER_MIN_FOLLOWING": "0",
        "FOLLOW_USER_MAX_FOLLOWING": "1000000",
        "USERS_TO_FOLLOW": "lelasohnabaka,vixeniaaa,gonkgonk666,msliababy,grungeeaesth",
        "HEADLESS": "false"
      },
      "error_file": "./logs/miyakiseki.log",
      "time": false,
      "autorestart": true,
      "max_restarts": 10,
      "restart_delay": 5000
    },
    {
      "name": "ladymcbeth.rells",
      "script": "./single_instance.js",
      "instances": 1,
      "exec_mode": "fork",
      "env": {
        "INSTANCE_ID": "3",
        "PROXY_IP": "82.163.175.153",
        "PROXY_USERNAME": "kamzza",
        "PROXY_PASSWORD": "bJXwSnBLy9",
        "PROXY_PORT": "50101",
        "BACKUP_PROXY_IP": "77.47.240.226",
        "INSTAGRAM_SESSIONID": "75037996132%3ARJbUaZdlrwS7iv%3A26%3AAYeCCJDf3sP6US1twTFk3jRA6brtoW9U2NfOyguzpg",
        "INSTAGRAM_USERNAME": "ladymcbeth.rells",
        "MAX_FOLLOWS_PER_HOUR": "25",
        "MAX_FOLLOWS_PER_DAY": "150",
        "MAX_LIKES_PER_DAY": "50",
        "FOLLOW_USER_RATIO_MIN": "0.0",
        "FOLLOW_USER_RATIO_MAX": "999999.0",
        "MINIMUM_POST_COUNT": "0",
        "MAXIMUM_POST_COUNT": "999999",
        "SHOULD_LIKE_POSTS": "true",
        "POSTS_TO_LIKE": "2",
        "FOLLOW_USER_MIN_FOLLOWERS": "0",
        "FOLLOW_USER_MAX_FOLLOWERS": "999999",
        "FOLLOW_USER_MIN_FOLLOWING": "0",
        "FOLLOW_USER_MAX_FOLLOWING": "999999",
        "USERS_TO_FOLLOW": "lelasohnabaka,vixeniaaa,gonkgonk666,msliababy,grungeeaesth",
        "HEADLESS": "false"
      },
      "error_file": "./logs/ladymcbeth.rells.log",
      "time": false,
      "autorestart": true,
      "max_restarts": 10,
      "restart_delay": 5000
    }
  ]
}
